export { AboutPage } from './AboutPage'
export { CaseDetailPage } from './CaseDetailPage'
export { CasesPage } from './CasesPage'
export { ContactPage } from './ContactPage'
export { HomePage } from './HomePage'
export { ServicesPage } from './ServicesPage'
